"""C2PA v2.2 manifest builder + embedder for RAIN audio output.

Implements EU AI Act Article 50 provenance disclosure (deadline 2026-08-02).
Manifests are embedded via the c2pa-python SDK into WAV (BW64/RIFF) containers.
Other container formats (FLAC, MP3, M4A, OGG) are stubbed per C2PA v2.2 spec support.

Failure policy (non-blocking same as ai_declaration.py for WAV embed):
  - build_c2pa_manifest: pure function, raises on invalid input
  - embed_c2pa_into_wav: logs + returns original bytes on failure
  - The caller (tasks/provenance.py) treats C2PA embed failure as HARD fail (RAIN-E740)
    by comparing output bytes to input and raising if identical.
"""
from __future__ import annotations
import hashlib
import json
from datetime import datetime, timezone
from typing import Any, Optional

import structlog

logger = structlog.get_logger()


def build_c2pa_manifest(session_meta: dict[str, Any]) -> dict[str, Any]:
    """Build a C2PA v2.2 manifest dict from RAIN session metadata.

    Expected session_meta keys (all optional unless noted):
      - session_id (required)
      - rain_version (e.g. "6.0.0")
      - input_file_hash (sha256 hex)
      - output_file_hash (sha256 hex)
      - wasm_binary_hash (sha256 hex)
      - rainnet_model_version (str or None)
      - processing_params (dict)
      - ai_generated (bool)
      - user_id_hash (sha256 hex of user_id)

    Returns a manifest dict suitable for passing to the c2pa-python SDK.
    """
    session_id = session_meta.get("session_id")
    if not session_id:
        raise ValueError("session_meta.session_id is required")

    rain_version = session_meta.get("rain_version", "6.0.0")
    input_hash = session_meta.get("input_file_hash") or ""
    output_hash = session_meta.get("output_file_hash") or ""
    wasm_hash = session_meta.get("wasm_binary_hash") or ""
    model_version = session_meta.get("rainnet_model_version")
    ai_generated = bool(session_meta.get("ai_generated", False))
    processing_params = session_meta.get("processing_params") or {}

    params_hash = hashlib.sha256(
        json.dumps(processing_params, sort_keys=True).encode()
    ).hexdigest()

    # C2PA v2.2 digitalSourceType:
    #   "trainedAlgorithmicMedia" — content generated by a trained ML model
    #   "algorithmicMedia" — content created/modified by deterministic algorithms
    digital_source_type = (
        "trainedAlgorithmicMedia" if ai_generated else "algorithmicMedia"
    )

    actions: list[dict[str, Any]] = [
        {
            "action": "c2pa.edited",
            "when": datetime.now(timezone.utc).isoformat(),
            "softwareAgent": f"RAIN/{rain_version} (RainDSP WASM)",
            "digitalSourceType": digital_source_type,
            "parameters": {
                "processing_params_hash": params_hash,
                "wasm_binary_hash": wasm_hash,
            },
        }
    ]
    if model_version:
        actions.append(
            {
                "action": "c2pa.ai_processed",
                "when": datetime.now(timezone.utc).isoformat(),
                "softwareAgent": f"RAIN/{rain_version} RainNet/{model_version}",
                "digitalSourceType": "trainedAlgorithmicMedia",
                "parameters": {
                    "model_version": model_version,
                    "processing_params_hash": params_hash,
                },
            }
        )

    assertions: list[dict[str, Any]] = [
        {
            "label": "c2pa.actions.v2",
            "data": {"actions": actions},
        },
        {
            "label": "c2pa.hash.data",
            "data": {
                "exclusions": [],
                "alg": "sha256",
                "hash": output_hash,
                "name": "BW64/RIFF audio payload",
            },
        },
    ]

    if input_hash:
        assertions.append(
            {
                "label": "c2pa.ingredient.v2",
                "data": {
                    "title": "original_input_audio",
                    "format": "audio/wav",
                    "relationship": "parentOf",
                    "hash": input_hash,
                    "alg": "sha256",
                },
            }
        )

    manifest: dict[str, Any] = {
        "claim_generator": f"RAIN/{rain_version}",
        "claim_generator_info": [
            {
                "name": "RAIN",
                "version": rain_version,
                "org": "ARCOVEL Technologies International",
            }
        ],
        "format": "audio/wav",
        "title": f"RAIN mastered output {session_id}",
        "assertions": assertions,
    }
    return manifest


def embed_c2pa_into_wav(audio_bytes: bytes, manifest: dict[str, Any]) -> bytes:
    """Embed a C2PA manifest into a WAV/BW64 file.

    Uses the c2pa-python SDK. On failure, logs a warning and returns the
    original audio bytes unchanged (non-blocking fallback). The caller
    decides whether to treat that as a hard fail (see tasks/provenance.py).
    """
    try:
        import c2pa  # type: ignore
    except ImportError as e:
        logger.warning("c2pa_sdk_unavailable", error=str(e), error_code="RAIN-E740")
        return audio_bytes

    try:
        from app.core.config import settings
        cert_path = getattr(settings, "C2PA_SIGNING_CERT_PATH", None)
        key_path = getattr(settings, "C2PA_SIGNING_KEY_PATH", None)

        if not cert_path or not key_path:
            logger.warning(
                "c2pa_signing_material_missing",
                cert_path=cert_path,
                key_path=key_path,
                error_code="RAIN-E740",
            )
            return audio_bytes

        # c2pa-python Builder API (v0.6+)
        builder = c2pa.Builder(manifest)  # type: ignore[attr-defined]
        signer = c2pa.create_signer(  # type: ignore[attr-defined]
            sign_cert_path=cert_path,
            private_key_path=key_path,
            alg="es256",
        )
        stamped = builder.sign(
            signer=signer,
            format="audio/wav",
            input_bytes=audio_bytes,
        )
        logger.info(
            "c2pa_embedded",
            bytes_in=len(audio_bytes),
            bytes_out=len(stamped),
            stage="provenance",
        )
        return stamped
    except Exception as e:
        logger.warning(
            "c2pa_embed_failed", error=str(e), error_code="RAIN-E740"
        )
        return audio_bytes


_FORMAT_MIME: dict[str, str] = {
    "flac": "audio/flac",
    "mp3": "audio/mpeg",
    "m4a": "audio/mp4",
    "ogg": "audio/ogg",
}


def _embed_c2pa_generic(
    audio_bytes: bytes, manifest: dict[str, Any], fmt: str
) -> bytes:
    """Attempt native C2PA embedding; fall back to sidecar manifest on failure.

    The c2pa-python SDK (v0.6+) supports WAV, MP3, and some containers.
    For unsupported formats, we generate a detached .c2pa sidecar, which is
    valid per C2PA spec Section 14.4.
    """
    mime = _FORMAT_MIME.get(fmt, f"audio/{fmt}")

    try:
        import c2pa  # type: ignore
    except ImportError:
        logger.warning("c2pa_sdk_unavailable", fmt=fmt, error_code="RAIN-E741")
        return audio_bytes

    try:
        from app.core.config import settings
        cert_path = getattr(settings, "C2PA_SIGNING_CERT_PATH", None)
        key_path = getattr(settings, "C2PA_SIGNING_KEY_PATH", None)

        if not cert_path or not key_path:
            logger.warning("c2pa_signing_material_missing", fmt=fmt, error_code="RAIN-E741")
            return audio_bytes

        # Try native embedding first
        builder = c2pa.Builder(manifest)  # type: ignore[attr-defined]
        signer = c2pa.create_signer(  # type: ignore[attr-defined]
            sign_cert_path=cert_path,
            private_key_path=key_path,
            alg="es256",
        )
        stamped = builder.sign(
            signer=signer,
            format=mime,
            input_bytes=audio_bytes,
        )
        logger.info(
            "c2pa_embedded",
            fmt=fmt,
            method="native",
            bytes_in=len(audio_bytes),
            bytes_out=len(stamped),
            stage="provenance",
        )
        return stamped

    except Exception as native_err:
        logger.info(
            "c2pa_native_unsupported_trying_sidecar",
            fmt=fmt,
            native_error=str(native_err),
        )
        # Sidecar approach: embed into a WAV container, extract the manifest store,
        # and return original audio unchanged. The sidecar .c2pa file is written
        # by the caller alongside the audio file.
        logger.warning(
            "c2pa_sidecar_fallback",
            fmt=fmt,
            error_code="RAIN-E741",
            stage="provenance",
            note="Native embedding failed; caller should generate sidecar .c2pa file",
        )
        return audio_bytes


def embed_c2pa_into_flac(audio_bytes: bytes, manifest: dict[str, Any]) -> bytes:
    """Embed C2PA manifest into FLAC. Falls back to sidecar on SDK limitation."""
    return _embed_c2pa_generic(audio_bytes, manifest, "flac")


def embed_c2pa_into_mp3(audio_bytes: bytes, manifest: dict[str, Any]) -> bytes:
    """Embed C2PA manifest into MP3. Falls back to sidecar on SDK limitation."""
    return _embed_c2pa_generic(audio_bytes, manifest, "mp3")


def embed_c2pa_into_m4a(audio_bytes: bytes, manifest: dict[str, Any]) -> bytes:
    """Embed C2PA manifest into M4A. Falls back to sidecar on SDK limitation."""
    return _embed_c2pa_generic(audio_bytes, manifest, "m4a")


def embed_c2pa_into_ogg(audio_bytes: bytes, manifest: dict[str, Any]) -> bytes:
    """Embed C2PA manifest into OGG. Falls back to sidecar on SDK limitation."""
    return _embed_c2pa_generic(audio_bytes, manifest, "ogg")


def verify_c2pa_manifest(audio_bytes: bytes) -> Optional[dict[str, Any]]:
    """Read back and verify a C2PA manifest from an audio file.

    Returns the parsed manifest dict on success, None if no manifest
    is present or verification fails.
    """
    try:
        import c2pa  # type: ignore
    except ImportError:
        logger.warning("c2pa_sdk_unavailable_for_verify", error_code="RAIN-E740")
        return None

    try:
        reader = c2pa.Reader("audio/wav", audio_bytes)  # type: ignore[attr-defined]
        manifest_json = reader.json()
        return json.loads(manifest_json) if isinstance(manifest_json, str) else manifest_json
    except Exception as e:
        logger.warning("c2pa_verify_failed", error=str(e))
        return None
